### ISSUE TITLE
RENEW and RETURN request should only be allowed with strict enforcement of registered device ID (passed in templated URI, and checked in events history for latest status)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#105]
...additionally, the RETURN and RENEW links in LSD JSON should only be allowed if REGISTER is present too, which forces devices to submit their ID before reading the publication, etc.

RETURN:
https://github.com/readium/readium-lcp-server/blob/manage-frontend/lsdserver/api/license_status.go#L293

RENEW:
https://github.com/readium/readium-lcp-server/blob/manage-frontend/lsdserver/api/license_status.go#L389

In both cases, the absence of device-id in the templated URL is tolerated.

If present, then the last known device-status is inferred from the most recent item in the recorded "events" list, and this status is checked (4 possible values: REGISTER(ed), RENEW(ed), RETURN(ed), or no-event/empty-status).
For RENEW, the device-id passed in the templated URL must indeed have been registered as a precondition.
This means that in cases when the LSD "register" JSON link is not included, then client apps must ensure *not* to pass the device-id in subsequent RENEW requests. Or, more logically, we can enforce that the server requires the "register" link to be present in the LSD JSON, when the RENEW link is present.

For RETURN: same as RENEW.

**Comment by llemeurfr** [comment]
I totally agree with that. The Readium LCP server now enforces a similar rule in license_status.go and I'll request an evolution of the spec.

**Comment by llemeurfr** [comment]
Finally discussed in [a discussion about the sepc evolution](/readium/readium-lcp-specs/issues/14) and rejected by the creators of the spec, with good arguments. I'll remove the check in the codebase.
