### ISSUE TITLE
Use RAML to design the REST API

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#112]
TODO: document the API using:
http://raml.org

**Comment by llemeurfr** [comment]
Go implementation in https://github.com/Jumpscale/go-raml.

**Comment by atomotic** [comment]
I made this https://github.com/atomotic/readium-lcp-server-api-doc a couple of years back and almost forgot, I've fixed a few things lately. The raml schema is handwritten, I've not found a good solution for automatic schema generation from Go http handlers. I described almost everything (with the same text) as is on [lcp wiki](https://github.com/readium/readium-lcp-server/wiki)

There is also a [action](https://github.com/atomotic/readium-lcp-server-api-doc/blob/master/.github/workflows/node.js.yml) building and publishing on github pages, result here: 
https://atomotic.github.io/readium-lcp-server-api-doc/

It's still incomplete, some things needs to be tweaked, mainly errors and example responses (for example wiki pages are linking some [broke content ](https://readium.org/licensed-content-protection/error/notfound)).

If you think it is correct we can revise things together, than you can fork or include raml in main lcp repo?

**Comment by llemeurfr** [comment]
@atomotic, could we update this work and fork it after the next version of the v1.x LCP server is released (in a few weeks)?

**Comment by atomotic** [comment]
Sure! i can transfer the repo to readium github if you want.
The Api should be complete, maybe the examples needs some cleaning.

**Comment by llemeurfr** [comment]
In the LCP Server v2, API documentation will use Swagger.
