### ISSUE TITLE
SHA256 checksum calculation (hasher) should iteratively consume buffered stream, not whole file

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#114]
https://github.com/readium/readium-lcp-server/blob/manage-frontend/pack/pipeline.go#L159
```go
	hasher := sha256.New()
	encryptedFileInfo.File.Seek(0, 0)
	written, err := io.Copy(hasher, encryptedFileInfo.File)
	//hasher.Write(s)
	if err != nil {
		r.Error = err
		return nil, nil
	}
	encryptedFileInfo.Size = written
	encryptedFileInfo.Sha256 = hex.EncodeToString(hasher.Sum(nil))
```

https://github.com/readium/readium-lcp-server/blob/manage-frontend/lcpencrypt/lcpencrypt.go#L135
```go
func getChecksum(filename string) string {
	hasher := sha256.New()
	s, err := ioutil.ReadFile(filename)
	hasher.Write(s)
	if err != nil {
		return ""
	}
	return hex.EncodeToString(hasher.Sum(nil))
}
```

**Comment by llemeurfr** [comment]
ioutil.ReadFile calls have been removed previously. 

io.Copy is using a Reader and a Writer, therefore "streamed". See https://medium.com/learning-the-go-programming-language/streaming-io-in-go-d93507931185
