### ISSUE TITLE
shiny frontend: UserKey.Hint (LCPL text_hint), hard-coded default value

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#131]
@snemegeer 

https://github.com/readium/readium-lcp-server/blob/develop/frontend/webpurchase/webpurchase.go#L225
`userKey.Hint = "Enter your passphrase"`

This should be configurable: "text hint" could either be a server-wide `config.yaml` setting, or a per-license choice (user-defined, via the HTML UI).

**Comment by llemeurfr** [comment]
Better, we must allow the user to enter a passphrase hint and store it in the frontend database, along with his passphrase.

**Comment by llemeurfr** [comment]
The hint is mandatory, the field is named "Passphrase hint".

**Comment by danielweck** [comment]
Right, and the passphrase hint ; just like the passphrase itself ; can be edited by the user (via the frontend HTML form). Any new LCP license generated after these edits would contain the updated data.

**Comment by snemegeer** [comment]
Agreed, it should be stored in the frontend db (and this is actually missing).

**Comment by llemeurfr** [comment]
done
