### ISSUE TITLE
cancel method in LSD server fails when license is registered

### ISSUE THREAD

**Issue by snemegeer** [readium/readium-lcp-server#132]
//[CancelLicenseStatus ](https://github.com/readium/readium-lcp-server/blob/develop/lsdserver/api/license_status.go#L650) cancel or revoke (according to the status) a license

[This status verification](https://github.com/readium/readium-lcp-server/blob/develop/lsdserver/api/license_status.go#L668) (must equal READY status) makes the revocation of a license impossible. After registering a license, the status becomes ACTIVE, and as a result this method fails.

**Comment by danielweck** [comment]
Indeed:
```go
	if licenseStatus.Status != status.STATUS_READY {
```
...should be: 
```go
	if licenseStatus.Status != status.STATUS_READY && licenseStatus.Status != status.STATUS_ACTIVE {
```
https://github.com/readium/readium-lcp-server/blob/develop/lsdserver/api/license_status.go#L668

Do you want to create a pull request (against develop)?

**Comment by danielweck** [comment]
During our tests, we also need to make sure that the status is correctly updated:
```go
licenseStatus.Status = parsedLs.Status
```
given by the parsed LSD `parsedLs.Status` from the HTTP request.
https://github.com/readium/readium-lcp-server/blob/develop/lsdserver/api/license_status.go#L700

**Comment by snemegeer** [comment]
I'm correcting this (with btw exactly what you wrote  :) )

**Comment by snemegeer** [comment]
I was thinking to do this directly in the develop branch

**Comment by llemeurfr** [comment]
The current code seems a bit naive. I would propose checking
- if the target status is "cancelled", that the current status is "ready"
-  if the target status is "revoked", that the current status is "active"
Other cases should give an error.

**Comment by danielweck** [comment]
I've updated my comment above regarding the `apilsd.CancelLicenseStatus` HTTP (authenticated `PATCH`) route.
So, should we add cancel/revoke action buttons in the "shiny frontend", or should be just rely on the fact that `return` does pretty much the same thing:
https://readium.github.io/readium-lsd-specification/#34-returning-a-publication
'...status with its value set to "returned" if the status was previously set to "active" or "cancelled" if the status was previously set to "ready"'
```go
case status.STATUS_ACTIVE:
		licenseStatus.Status = status.STATUS_RETURNED
break
case status.STATUS_READY:
		licenseStatus.Status = status.STATUS_CANCELLED
break
```
https://github.com/readium/readium-lcp-server/blob/develop/lsdserver/api/license_status.go#L279

**Comment by llemeurfr** [comment]
In fact we should be more flexible, but with the same result:
- if the target status is "cancelled", that the current status is "ready"
- if the target status is "revoked", that the current status is "ready" or "active".

That seems better after reading the spec: 
cancelled: The license is no longer active because it was cancelled prior to activation.
revoked: The license is no longer active, it has been invalidated by the Issuer

**Comment by danielweck** [comment]
I agree with checking for inconsistent use of CANCELLED vs. REVOKED.

**Comment by llemeurfr** [comment]
For proper testing, I think that explicit cancel and revoke buttons are best. We can open an issue for that and Léo will be able to implement it in the frontend.

**Comment by danielweck** [comment]
Fixed in https://github.com/readium/readium-lcp-server/commit/cb5946a906e60508c089edcb5d12bf0c2f3a57ba

**Comment by snemegeer** [comment]
and [61a7413](https://github.com/readium/readium-lcp-server/commit/61a74130a0d514f2634d84747475c5bee63b33e5) 
* if the target status is "revoked", that the current status is "ready" or "active".

**Comment by danielweck** [comment]
Oh, I see, there was an additional intermediary commit:
https://github.com/readium/readium-lcp-server/commit/61a74130a0d514f2634d84747475c5bee63b33e5
:)

...so the overall code diff is (as a pull request would have displayed):
https://github.com/readium/readium-lcp-server/compare/d866747ac7bbaa32ecde02a87af75ca1f949e0a3...f3b8386ff9baecb8d45cf58725e0c330c54c069c
