### ISSUE TITLE
shiny frontend: remove user / publication => what happens to already-created purchases?

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#133]

**Comment by snemegeer** [comment]
Actually, nothing if the frontend has no user info, the license will still be correct.  I think problems will arise when the client reader contacts the frontend to contact the lcp server behind it. (and the purchase is not found anymore).  The link in the license may not work anymore.  Renewals and returns of loans will not work, the license if already downloaded should work.
Why would someone want to remove a user ? 
This is about the current frontend ? or you mean a real frontend /webshop?

**Comment by danielweck** [comment]
I mean the test server deployed at edrlab.org ("shiny frontend").

**Comment by llemeurfr** [comment]
See https://github.com/readium/readium-lcp-server/blob/master/frontend/webpublication/webpublication.go#L319
-> file is deleted from the storage, all purchases relative to the publication are suppressed, the publication is suppressed from the frontend db, *but not from the lcpserver*.

See https://github.com/readium/readium-lcp-server/blob/master/frontend/webuser/webuser.go#L115-L133
-> all purchases relative to the publication are suppressed, the user is suppressed.
