### ISSUE TITLE
frontend: list licenses with a filter

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#138]
The License Status Server provides a list of licenses filtered by a min number of registered devices (https://github.com/readium/readium-lcp-server/wiki/License-status-server).

It will be good to get this list appear on the frontend. This view is similar to the "Purchases" view. 

A text field labelled "Min registered devices" allows entering a numeric positive value (eg 10).
On submit, a table appear below, with 
1/ data dynamically added from the frontend db: "Publication", "User", "Type" found via the license id of the REST response;
2/ the fields provided by the REST response: "devices", "status", "message";
3/ a status button.

If the status button is selected, the user is moved to the Status page, where he may revoke the license. 
No need for a pagination is this view, as this is only a test server.

**Comment by Scarsniik** [comment]
Added in 026efa7
