### ISSUE TITLE
Unclear Event Type in specification

### ISSUE THREAD

**Issue by camill-a** [readium/readium-lcp-server#146]
The `Type` field of the `Event` is currently described as: 

![screen shot 2017-09-06 at 5 19 42 pm](https://user-images.githubusercontent.com/2509963/30119914-a7783cdc-9327-11e7-8f3e-92cf4c6017ed.png)

I spent some time figuring out that it was refering to:  `"register"`, `"renew"` and `"return"`.

It would be nice if it also had a listing of the possible values as done for the `Status` perviously in the document.

**Comment by danielweck** [comment]
Specification reference:
https://readium.github.io/readium-lsd-specification/#27-events

**Comment by danielweck** [comment]
Note that the "activate" example seems wrong:
https://readium.github.io/readium-lsd-specification/#13-example

**Comment by HadrienGardeur** [comment]
Issues should be filed at: https://github.com/readium/readium-lcp-specs/issues

**Comment by llemeurfr** [comment]
I filled the issue at /readium/readium-lcp-specs/issues/13.
