### ISSUE TITLE
Dates normalization

### ISSUE THREAD

**Issue by camill-a** [readium/readium-lcp-server#147]
//[...]   
"rights":{
      "print":100,
      "copy":2048,
      "start":"2017-08-30T03:39:24.687663655Z",
      "end":"2017-08-31T12:40:00+09:00"
   },
// [...]
The variations encountered in the LCP server dates should be normalized, to simplify their usage.

**Comment by llemeurfr** [comment]
Done in the development branch and deployed on the test servers.
