### ISSUE TITLE
RCS test server 10013 incorrect license link in LSD

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#150]
`http://BASE/licenses/UUID`
should be:
`http://BASE/api/v1/purchases/license/UUID`

**Comment by llemeurfr** [comment]
I disagree with this. The frontend API is described in [the server wiki](/readium/readium-lcp-server/wiki/Test-frontend-server) and exposes `http://BASE/licenses/UUID`. 
The second URL is used by the react client to find a license knowing a purchase id, i.e. using `http://BASE/api/v1/purchases/UUID/license`.

**Comment by danielweck** [comment]
I filed this issue after observing failures of the LSD client to fetch updated licences (first link was dead, second worked).
So, is that problem now fixed? (I haven't tried recently)

**Comment by danielweck** [comment]
Well, both 10013 and 11013 servers currently generate `/api/v1/licenses/ID` URL for the LCP license link exposed in the LSD JSON. Is that correct?

For example:

**11013**

https://DOMAIN.ORG/11013/purchases/63/status

=> LCP provides LSD URL:
https://DOMAIN.ORG/11012/licenses/0067ed43-acb6-4bed-a67d-10208145c9f2/status

=> LSD provides LCP URL:
https://DOMAIN.ORG/11013/api/v1/licenses/0067ed43-acb6-4bed-a67d-10208145c9f2

**10013**

https://DOMAIN.ORG/10013/purchases/160/status

=> LCP provides LSD URL:
https://DOMAIN.ORG/10012/licenses/bc50e205-b682-462f-a34e-ee1583357087/status

=> LSD provides LCP URL:
https://DOMAIN.ORG/10013/api/v1/licenses/bc50e205-b682-462f-a34e-ee1583357087

My bug report (this issue) was because in the past, LCP server 10013 was *not* generating `/api/v1/licenses/ID`, but instead `/licenses/ID` which was failing to resolve (`{"title":"Not Found","status":404}`). So in my code I had to implement a hack (alternate fetch URL). Now that the 10013 server is fixed, I can remove my code hack.

However, I also want to double-check with you that the `/api/v1/licenses/ID` URL is correct in the LSD JSONs, because `/licenses/ID` still returns `{"title":"Not Found","status":404}`.

**Comment by llemeurfr** [comment]
@danielweck you're right, I fixed the server to generate `/api/v1/license/ID` for getting the license from the frontend server, and more generically `/api/v1/...`for interacting with the frontend. It was originally Cyrille's request I guess, to version the frontend api (which is always a good practice). But you'll have noted that the LSD server API is still not versioned.
