### ISSUE TITLE
frontent server; authentication to the LSD server must be configurable

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#151]
In /readium/readium-lcp-server/blob/fix/frontend/frontend/server/server.go#L187, one finds a static authentication corresponding to a specific test install. 
It must be replaced by values found in config.yaml.

**Comment by Scarsniik** [comment]
It fixed on 41efed4

**Comment by llemeurfr** [comment]
Thanks @Scarsniik
