### ISSUE TITLE
MySQL compatibility

### ISSUE THREAD

**Issue by MelBookeen** [readium/readium-lcp-server#160]
Hello,
It seems that MySql compatibility is broken at some time.
On my fork, for instance, I have to made changes on files because instruction "CREATE INDEX IF NOT EXISTS" doesn't exist and there is a problem on circular dependencies. Files changes:

- [dbmodel/database script.sql](https://github.com/MelBookeen/readium-lcp-server/blob/master/dbmodel/database%20script.sql)
-  [license_statuses/license_statuses.go](https://github.com/MelBookeen/readium-lcp-server/blob/master/license_statuses/license_statuses.go)
-  [transactions/transactions.go](https://github.com/MelBookeen/readium-lcp-server/blob/master/transactions/transactions.go)

This changes are not meant to last and for instance could break compatibility with the other DBMS.
Therefore, could you update scripts to make lcp-server compatible with MySQL ?

Thank's

**Comment by llemeurfr** [comment]
I have modified several sources to align the syntax of table creation and updated the sql script. This is committed in the develop branch. 
But I stumble with an issue: now that I removed the IF NOT EXISTS on the CREATE INDEX, my SQLite throws an error when starting the LSD server (as the DB is already installed).  
Before I put back the IF NOT EXISTS to satisfy current SQLite installs, does somebody knows a multi-db solution which would take care of existing indices on application start? 
Remember that we want the DB structure to be create dynamically, and the SQL script is mostly there for testing (it could even be removed if there is a misunderstanding about its use).

**Comment by llemeurfr** [comment]
I put temporarily put back  the IF NOT EXISTS on the CREATE INDEX in 7e56b9faf9acdecf430681091febe79967d4fb14.

Now let's discuss how to have the codebase supporting different SQL db, with SQL interop issues. 

One immediate solution is to use the existing "database" config parameter as a source for switching between different SQL flavors on table creation functions (our simple insert/update/delete commands are not impacted by SQL interop issues). 
We will then use a trick like the one shown in https://play.golang.org/p/C0nDgOfrUW 

Do you see other lightweight solution?

**Comment by MelBookeen** [comment]
IF NOT EXISTS on the CREATE INDEX isn't the only problem.
I had to change content.encrytion_key and license.user_key_has in varbinary(64) to correctly save the data.

Did you encounter the same problem ?

**Comment by llemeurfr** [comment]
I've seen that in your branch, but did not experimented it as I don't use MySQL on our test servers. 

Let's tackle the problem generically, as there may be other issues for PostgresQL, MS SQL Server, DB2 or Oracle users later.

**Comment by MelBookeen** [comment]
The other solution is to have a different file for create database but I'm not sure it's possible.

**Comment by llemeurfr** [comment]
We find table creations in 
license/store.go
index/index.go
license_statuses/license_statuses.go
transactions/transactions.go
frontend/webuser/webuser.go
frontend/wepurchase/webpurchase.go
frontend/webpublication/webpublication.go
frontend/weblicense/weblicense.go
(plus database script.sql, but this one is not used in practice)

Creating a different go file for each db would not work.

**Comment by snemegeer** [comment]
I think it is quite hard to handle all databases-engines in the go code.  
Creating a database may need additional db-user rights. 
The go code could use sqllite to demonstrate the code easily, but in the event someone decides to use a different db engine, this is detected in the code (database != sqlite), and no metadata script is executed on the db.
It is up to the user to create the db correctly before connecting the server.
One script per supported db-engine could be provided.  
The go code only connects mysql/mssql/... , and does not alter the database, unless it is sqlite ?

**Comment by llemeurfr** [comment]
Yes, this is an even simpler solution. Do other users of this codebase agree with @snemegeer proposal? @MelBookeen

**Comment by MelBookeen** [comment]
It's ok

**Comment by llemeurfr** [comment]
I added a test of the use of sqlite in 2fb45d0746ef7d8d9d867c8c89441c5f17a1cb50. A db creation script must now be used if MySQL or any other db different from sqlite is used. I renamed the sqlite creation script in 22e2c4d9ea929e4505fd5be488a0684212a7f291, removing the "if not exists" command (it's an initialization script after all). 

@MelBookeen please make a copy of this script as "mysql db setup.sql", modify it so it fits MySQL requirements, and propose a Pull Request, on the development branch.

Note: In case the db structure evolves, we'll have to propose db change scripts.

**Comment by MelBookeen** [comment]
I add the script : https://github.com/readium/readium-lcp-server/pull/164/commits/3993f9c09f01d9c2986a19507b487b9cb90d0e5d
