### ISSUE TITLE
LCP Server Build Error

### ISSUE THREAD

**Issue by jaschrock** [readium/readium-lcp-server#161]
When I go to build the lcp server off of the development branch, I get the following: 

./lcpserver.go:213:10: s3config.ID undefined (type storage.S3Config has no field or method ID, but does have Id)

downloaded the code just today - 19.12.2017. 

Is this an issue in my configuration or in the code?

Thanks

**Comment by llemeurfr** [comment]
It should be a config issue, you've activated a prototype S3 storage functionality (for storing encrypted content assets); certainly by putting "storage / mode: 's3' " in your lcp config file. This functionality has not been fully tested, therefore for now you should use a filesystem storage, as indicated in the config samples.

**Comment by jaschrock** [comment]
I had just modified the base yaml file and didn't change anything other than my particulars (with some that probably still need tweaked). This is what I have in my config.yaml file. It just says filesystem. 
profile: "basic"
lcp:
    host: "127.0.0.1"
    port: 8989
    public_base_url: "http://127.0.0.1:8989"
    database: "sqlite3://file:/work/lcp.sqlite?cache=shared&mode=rwc"
    auth_file: "/readiumlcp/lcpconfig/htpasswd"
storage:
    filesystem:
        directory: "/work/storage"
certificate:
    cert: "/work/cert.pem"
    private_key: "/work/privkey.pem"
license:
    links:
        status: "http://127.0.0.1:8990/licenses/{license_id}/status"
        hint: "http://127.0.0.1:8991/static/hint.html"
        publication: "http://127.0.0.1:8991/licenses/{license_id}/publication"
lsd:
    public_base_url:  "http://127.0.0.1:8990"
lsd_notify_auth:
    username: "adm_username"
    password: "adm_password"

Thanks

**Comment by llemeurfr** [comment]
I now see this is a build issue, not a run issue. s3config.Id was renamed s3config.ID (golint advice) in storage/s3.go and in lcpserver/lcpserver.go inside the same commit  3db059aadd53e4f100ab56f1d962c701d4ac0958, on Oct 23. 
All I can imagine is a checkout issue when you moved from the master to the develop branch (?)

**Comment by llemeurfr** [comment]
any news @jaschrock?

**Comment by jaschrock** [comment]
Sorry, haven't had a chance to get back to this yet. I will try and grab the latest from Git and see if that works. Maybe in the next 2-3 weeks, if not then probably a good month or more yet...
Thanks for checking.

**Comment by jaschrock** [comment]
I have downloaded the latest development branch and no longer get that error when I build things. So, I am making progress! 
I did have a problem, though, trying to start the front-end server. When I tried to do an npm start, it gave me an error about a missing ./config.js file. I created a blank file and it gave me an error about frontend not being defined. When I just renamed the bs-config.js file, it allowed the server to start (on port 3000) and the page comes up for the front-end but the links do not do anything. This, though, may be since I don't have much else tested yet? 

I was able to encrypt a file fine (presumably) and the LCPServer test admin came up but I wasn't sure exactly what to put in where there are options for:
Package identifier, passphrase, user identifier, user email, license fagment to send in HTTP request and then puttons for Generate License nad Generate Protected publication. I couldn't find any documentation on using this utility. My next steps, of course, would be to:
1. encrypt the file (i think that is done), 
2. Presumably, generate a license for the file so it can be lent.
3. Loan the file for a particular timeframe and pull the file down to a reader/device. 

To be honest, I am uncertain where to find the steps to move from the initial installation to actually accomplish these events. Maybe if the front-end was working I could look some through the code for this. Is there a demo video somewhere to show all the pieces working? I know there also are some certificate pieces that will be an issue at some point here. Can you point me to the proper documentation to go from here? 
Thanks

**Comment by llemeurfr** [comment]
Good to know that the install issue is solved now. I suggest to close this issue and I now open a new one on the new issue you're facing.
