### ISSUE TITLE
lcp server compilation error

### ISSUE THREAD

**Issue by MelBookeen** [readium/readium-lcp-server#167]
Hello,
I try to install the last verion of lcp but it doesn't working.
When I compile I get this error: `src/github.com/readium/readium-lcp-server/pack/pipeline.go:120: multiple-value uuid.NewV4() in single-value context`

It seems that github.com/satori/go.uuid has recently changed.

Can you solve the problem ?
Thank's

**Comment by llemeurfr** [comment]
This one is easy. See https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c#diff-04c6e90faac2675aa89e2176d2eec7d8
-> the guy has changed the signature of uuid.NewV4(), adding an error on return.
Best to follow the trend...

**Comment by llemeurfr** [comment]
Fixed by 538c2bf035b86050ce904c17d6ba1bc55051073d on the develop branch. PR created.

**Comment by llemeurfr** [comment]
Note that I had to I update go.uuid by `go get -u github.com/satori/go.uuid`, there is no automatic package update with Go. `go get -u all` will update all packages in $GOPATH.
