### ISSUE TITLE
starting the frontend server

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#169]
From @jaschrock:

> I did have a problem, though, trying to start the front-end server. When I tried to do an npm start, it gave me an error about a missing ./config.js file. I created a blank file and it gave me an error about frontend not being defined. When I just renamed the bs-config.js file, it allowed the server to start (on port 3000) and the page comes up for the front-end but the links do not do anything. This, though, may be since I don't have much else tested yet?

**Comment by llemeurfr** [comment]
First, it's worth noting that the frontend is not mandatory for an LCP license server: this is a testing tool that mimics how a real frontend should interact with the license and license status servers. It offers a way to import epub files and create publications, create users with their passphrase and hint, create and download licenses. Another way to test the license server is to use the http api directly (the API is detailed in the Wiki). 

Note also that config.js is an automatically generated file. 

For checking, I just tried the following (note: on OSX):
> cd $GOPATH/src/github.com/readium/readium-lcp-server/frontend/manage
> rm -rf node_modules
> rm config.js
> npm install
> npm start 

and yes I met:
/Users/laurentlemeur/Work/gospace/src/github.com/readium/readium-lcp-server/frontend/manage/node_modules/lite-server/lib/lite-server.js:33
[3]       throw (err);
[3] Error: ENOENT: no such file or directory, open './config.js'

So I did the following:
> cd ..
> frontend
... wait ... the server starts ...
> Ctrl-C
> ls manage
... config.js has been created
> cd manage
> npm start
... it just works, launches the frontend GUI
> Ctrl C
> cd ..
> frontend

Now you can open a browser and use the frontend URL (e.g. http://192.168.1.1:8991).
Be sure you're config.yaml is correct before you start the servers. 

conclusion: we have a small issue to solve, as config.js is not created with npm start, therefore the test fails if the frontend has never been started before.

**Comment by jaschrock** [comment]
That was very helpful. A couple of things to note:
1. I had forgotten, but after doing your "rm -rf node_modules" above, I ran into the error again: 
Error: ENOENT: no such file or directory, scandir '/work/src/github.com/readium/readium-lcp-server/frontend/manage/node_modules/node-sass/vendor'
I had to manually create this directory earlier and did this again. Also, in order for it to install correctly, I also had to issue the command: 
npm rebuild node-sass –force
After this, it let me install it. It seemed to only default in the ./manage directory to port 3000 so then I moved to my bin directory, after making some tweaks to the config.yaml file and that worked OK. 
One thing that I hadn't also done was to run the SQL commands in sqlite3 found in the dbmodel folder in GIT. I mention this in case others have the same issue searching the forums.
I have been able to success upload an epub and create a user. Also, to download the lcpl file. Still working next on the reader part, but that is out of scope for this thread. Thanks for your help.

**Comment by dauwhe** [comment]
> So I did the following:
> 
> > cd ..
> > frontend
> > ... wait ... the server starts ...
> > Ctrl-C
> > ls manage
> > ... config.js has been created
> > cd manage
> > npm start
> > ... it just works, launches the frontend GUI
> > Ctrl C
> > cd ..
> > frontend

Having a similar issue. I'm not quite sure what's going on above. What triggers the creation of config.js?

**Comment by danielweck** [comment]
The `frontend` executable creates the `config.js` file, which is a prerequisite for the fancy "manage" web interface (to be launched with `npm start` inside `frontend/manage/` https://github.com/readium/readium-lcp-server/tree/develop/frontend/manage ).

See:
https://github.com/readium/readium-lcp-server/blob/9c3b3715df77a66ad32199be0c6d95f65540e157/frontend/frontend.go#L121-L152

Note that the LCP server (`lcpserver` executable) also has its own legacy crappy test-only developer-mode static-HTML web interface ( https://github.com/readium/readium-lcp-server/tree/develop/lcpserver/manage ):

https://github.com/readium/readium-lcp-server/blob/9c3b3715df77a66ad32199be0c6d95f65540e157/lcpserver/lcpserver.go#L76-L104

**Comment by hvbnet** [comment]
I have same issue. 
I using windows to build and it has done successfully. but when start server got below error:

> 7:07:07 AM - Starting compilation in watch mode...
> [2]
> [3] C:\Users\h\go\src\github.com\readium\readium-lcp-server\frontend\manage\node_modules\lite-server\lib\lite-server.js:33
> [3]       throw err;
> [3]       ^
> [3]
> [3] Error: ENOENT: no such file or directory, open './config.js'
> [3]     at Object.openSync (fs.js:443:3)
> [3]     at Object.readFileSync (fs.js:343:35)
> [3]     at Object.<anonymous> (C:\Users\h\go\src\github.com\readium\readium-lcp-server\frontend\manage\bs-config.js:4:19)
> [3]     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> [3]     at Module.load (internal/modules/cjs/loader.js:653:32)
> [3]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> [3]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> [3]     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
> [3] lite-server --config=bs-config.js exited with code 1
> [2]
> [2] 7:07:12 AM - Found 0 errors. Watching for file changes.

**Comment by llemeurfr** [comment]
In the next major version of the software, the "frontend test server" will disappear, and therefore this config.js file also.
