### ISSUE TITLE
API generate licence - panic recovery (error)="runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by EmmanuelBk** [readium/readium-lcp-server#170]
Hi,

I have a readium-lcp-server issue when I use the API to generate a license (https://github.com/readium/readium-lcp-server/wiki/License-Server#generate-a-license)

1 - I generate a license with an email: test-2@test.fr -> the license is generated (reply 1)
2 - About an hour later, I generate new license with another email: test-1@test.fr (reply 2)
3 - And then, after the error, I can generate new licence with this email : test-1@test.fr. (reply 3)

Can you help me to solve this problem ?

Best regards, 

Informations
* readium-lcp-server : lcp-server master
* Data payload for user test-2@test.fr :
`$data = [
  'provider' => 'https://myprovider.com/',
  'user' => [
    'id' => 5f98b69a-1561-418b-8af8-805af4e9147b,
    'email' => test-2@test.fr,
    'encrypted' => ['email'],
  ],
  'encryption' => [
    'user_key' => [
      'text_hint' => 'Enter the email address which authentifies you on the library',
      'value' => wVyXJZ/wUqkDmz00fSvpCFLafnzMTGi7/GjxhmNTGzc=,
      'algorithm' => 'http://www.w3.org/2001/04/xmlenc#sha256',
    ],
  ],
  'rights' => [
    'copy' => 3,
  ],
];`

* Data payload for user test-1@test.fr :
`$data = [
  'provider' => 'https://myprovider.com/',
  'user' => [
    'id' => f7962f2e-e9c5-4c58-bec0-1ce13c94c926,
    'email' => test-1@test.fr,
    'encrypted' => ['email'],
  ],
  'encryption' => [
    'user_key' => [
      'text_hint' => 'Enter the email address which authentifies you on the library',
      'value' => uPwSnGI1/ufjFpxSx7mgasGObm39RbGApGmq/dpiFoU=,
      'algorithm' => 'http://www.w3.org/2001/04/xmlenc#sha256',
    ],
  ],
  'rights' => [
    'copy' => 3,
  ],
];`

* readium-lcp-server reply 1 :

`now=2018-03-07T15:01:14+0000 user=test1
2018/03/07 16:01:14 Generate License for content id 9782369760283
[negroni] 2018-03-07T16:01:14+01:00 | 201 | 	 298.844752ms | localhost:8989 | POST /contents/9782369760283/licenses 
2018/03/07 16:01:15 Notify Lsd Server of a new License with id f7962f2e-e9c5-4c58-bec0-1ce13c94c926 = 200`

* readium-lcp-server reply 2:

`now=2018-03-07T15:07:30+0000 user=test1
2018/03/07 16:07:30 Generate License for content id 9781908580818
[mysql] 2018/03/07 16:07:30 packets.go:36: unexpected EOF
[negroni] PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 26 [running]:
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7fe25487b050, 0xc42012a088, 0xc42007b6d0, 0xc42035c600)
	/go/src/github.com/urfave/negroni/recovery.go:159 +0xef
panic(0xac2960, 0x10ed430)
	/usr/local/go/src/runtime/panic.go:491 +0x283
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:2742 +0x75
database/sql.(*Rows).Close(0x0, 0x1, 0x0)
	/usr/local/go/src/database/sql/sql.go:2738 +0x3d
panic(0xac2960, 0x10ed430)
	/usr/local/go/src/runtime/panic.go:491 +0x283
sync.(*RWMutex).RLocker(...)
	/usr/local/go/src/database/sql/sql.go:2441
database/sql.(*Rows).Next(0x0, 0xb95c38)
	/usr/local/go/src/database/sql/sql.go:2441 +0x30
github.com/readium/readium-lcp-server/index.dbIndex.Get(0xc420073c20, 0xc420220000, 0x0, 0xc420220090, 0xc42035439f, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/readium/readium-lcp-server/index/index.go:63 +0x12d
github.com/readium/readium-lcp-server/index.(*dbIndex).Get(0xc42012c060, 0xc42035439f, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:1 +0xda
github.com/readium/readium-lcp-server/lcpserver/api.buildLicense(0xc4203591e0, 0x11042e0, 0xc4200f4b00, 0x0, 0xc4202235e8)
	/go/src/github.com/readium/readium-lcp-server/lcpserver/api/license.go:105 +0x100
github.com/readium/readium-lcp-server/lcpserver/api.GenerateLicense(0x7fe25487b050, 0xc42012a088, 0xc42035c800, 0x11042e0, 0xc4200f4b00)
	/go/src/github.com/readium/readium-lcp-server/lcpserver/api/license.go:281 +0x201
github.com/readium/readium-lcp-server/lcpserver/server.(*Server).handlePrivateFunc.func1(0x7fe25487b050, 0xc42012a088, 0xc42035c800)
	/go/src/github.com/readium/readium-lcp-server/lcpserver/server/server.go:157 +0xae
net/http.HandlerFunc.ServeHTTP(0xc4201fb280, 0x7fe25487b050, 0xc42012a088, 0xc42035c800)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201d29a0, 0x7fe25487b050, 0xc42012a088, 0xc42035c800)
	/go/src/github.com/gorilla/mux/mux.go:159 +0xed
github.com/urfave/negroni.Wrap.func1(0x7fe25487b050, 0xc42012a088, 0xc42035c600, 0xc42012c6a0)
	/go/src/github.com/urfave/negroni/negroni.go:46 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc4201faa20, 0x7fe25487b050, 0xc42012a088, 0xc42035c600, 0xc42012c6a0)
	/go/src/github.com/urfave/negroni/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x10fe600, 0xc4201faa20, 0xc4201faae0, 0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/rs/cors.(*Cors).ServeHTTP(0xc420073ea0, 0x7fe25487b050, 0xc42012a088, 0xc42035c600, 0xc42012c680)
	/go/src/github.com/rs/cors/cors.go:233 +0xe6
github.com/urfave/negroni.middleware.ServeHTTP(0x10fc5c0, 0xc420073ea0, 0xc4201faac0, 0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/urfave/negroni.(*Static).ServeHTTP(0xc42032a420, 0x7fe25487b050, 0xc42012a088, 0xc42035c600, 0xc42012c660)
	/go/src/github.com/urfave/negroni/static.go:34 +0x8c
github.com/urfave/negroni.middleware.ServeHTTP(0x10fc700, 0xc42032a420, 0xc4201faaa0, 0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/urfave/negroni.(*Logger).ServeHTTP(0xc42019fe60, 0x7fe25487b050, 0xc42012a088, 0xc42035c600, 0xc42012c640)
	/go/src/github.com/urfave/negroni/logger.go:66 +0x8b
github.com/urfave/negroni.middleware.ServeHTTP(0x10fc640, 0xc42019fe60, 0xc4201faa80, 0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc42007b6d0, 0x7fe25487b050, 0xc42012a088, 0xc42035c600, 0xc42012c620)
	/go/src/github.com/urfave/negroni/recovery.go:193 +0x8c
github.com/urfave/negroni.middleware.ServeHTTP(0x10fc6c0, 0xc42007b6d0, 0xc4201faa60, 0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa5
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/jeffbmartinez/delay.Middleware.ServeHTTP(0x7fe25487b050, 0xc42012a088, 0xc42035c600, 0xc42012c600)
	/go/src/github.com/jeffbmartinez/delay/delay.go:23 +0x7e
github.com/jeffbmartinez/delay.(*Middleware).ServeHTTP(0x1152b08, 0x7fe25487b050, 0xc42012a088, 0xc42035c600, 0xc42012c600)
	<autogenerated>:1 +0x5c
github.com/urfave/negroni.middleware.ServeHTTP(0x10fe580, 0x1152b08, 0xc4201faa40, 0x7fe25487b050, 0xc42012a088, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa5
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc42019fe30, 0x1102ac0, 0xc42035a0e0, 0xc42035c600)
	/go/src/github.com/urfave/negroni/negroni.go:96 +0xf5
net/http.serverHandler.ServeHTTP(0xc4200f4b00, 0x1102ac0, 0xc42035a0e0, 0xc42035c600)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42021c6e0, 0x1103280, 0xc4201303c0)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
now=2018-03-07T15:07:30+0000 panic recovery (error)="runtime error: invalid memory address or nil pointer dereference"`

* readium-lcp-server reply 3 :

`now=2018-03-07T15:08:09+0000 user=test1
2018/03/07 16:08:09 Generate License for content id 9781908580818
[mysql] 2018/03/07 16:08:09 statement.go:97: invalid connection
[negroni] 2018-03-07T16:08:09+01:00 | 201 | 	 257.25411ms | localhost:8989 | POST /contents/9781908580818/licenses 
2018/03/07 16:08:12 Notify Lsd Server of a new License with id 5f98b69a-1561-418b-8af8-805af4e9147b = 200`

**Comment by danielweck** [comment]
Trace:
https://github.com/readium/readium-lcp-server/blob/master/lcpserver/api/license.go#L105
https://github.com/readium/readium-lcp-server/blob/52a3444f04521420539d4e7dbdd3546b8eb533b2/lcpserver/api/license.go#L105

=>
https://github.com/readium/readium-lcp-server/blob/master/index/index.go#L60
https://github.com/readium/readium-lcp-server/blob/52a3444f04521420539d4e7dbdd3546b8eb533b2/index/index.go#L60

**Comment by danielweck** [comment]
The panic/recovery stacktrace indicates a crash inside Go's SQL implementation, related to the sync "locker" (code critical section):
https://golang.org/src/database/sql/sql.go#L2597
```go
func (rs *Rows) Next() bool {
	var doClose, ok bool
	withLock(rs.closemu.RLocker(), func() {
		doClose, ok = rs.nextLocked()
	})
	if doClose {
		rs.Close()
	}
	return ok
}
```

**Comment by EmmanuelBk** [comment]
Hi,

I come back to get some informations about this bug.
Do you or someone tried to reproduice it ? Is it being resolved  ?

Best regard.

**Comment by llemeurfr** [comment]
Seems to be related with the MySQL interface. I didn't find the time to install MySQL and test on my side. Did you try with SQLite to assert that it does not happen it this case?

**Comment by llemeurfr** [comment]
Closed as this problem was never raised again and MySQL support is quite better now.
