### ISSUE TITLE
Fix some MySQL issues

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#171]
Some instructions like PRAGMA JOURNAL_MODE are specific to  SQLite. We need at least to add tests of the DB type and find equivalents for other DBs. This is not done for PRAGMA JOURNAL_MODE in the frontend so far. 
 
With MySQL, it seems that some INSERT do break because the database fields are not declared as AUTO_INCREMENT (to be verified).

**Comment by giancanuz** [comment]
I have also faced issues with large primary keys in MariaDB. 
I have solved by setting:
innodb_file_format=Barracuda
innodb_large_prefix=1
in my.cnf

and by changing creation scripts in this way:
CREATE TABLE `content` (
    `id` varchar(255) NOT NULL,
    `encryption_key` varbinary(64) NOT NULL,
    `location` text NOT NULL,
    `length` bigint(20),
    `sha256` varchar(64)
) ROW_FORMAT=DYNAMIC;

alter table `content` ADD CONSTRAINT pkey_content primary key (id);

CREATE TABLE `license` (
    `id` varchar(255) PRIMARY KEY NOT NULL,
    `user_id` varchar(255) NOT NULL,
    `provider` varchar(255) NOT NULL,
    `issued` datetime NOT NULL,
    `updated` datetime DEFAULT NULL,
    `rights_print` int(11) DEFAULT NULL,
    `rights_copy` int(11) DEFAULT NULL,
    `rights_start` datetime DEFAULT NULL,
    `rights_end` datetime DEFAULT NULL,
    `content_fk` varchar(255) NOT NULL,
    `lsd_status` int(11) default 0,
    FOREIGN KEY(content_fk) REFERENCES content(id)
) ROW_FORMAT=DYNAMIC;

CREATE TABLE `license_status` (
    `id` int(11) PRIMARY KEY not null AUTO_INCREMENT,
    `status` int(11) NOT NULL,
    `license_updated` datetime NOT NULL,
    `status_updated` datetime NOT NULL,
    `device_count` int(11) DEFAULT NULL,
    `potential_rights_end` datetime DEFAULT NULL,
    `license_ref` varchar(255) NOT NULL,
    `rights_end` datetime DEFAULT NULL 
) ROW_FORMAT=DYNAMIC;

CREATE INDEX `license_ref_index` ON `license_status` (`license_ref`);

CREATE TABLE `event` (
    `id` int(11) PRIMARY KEY not null AUTO_INCREMENT,
    `device_name` varchar(255) DEFAULT NULL,
    `timestamp` datetime NOT NULL,
    `type` int NOT NULL,
    `device_id` varchar(255) DEFAULT NULL,
    `license_status_fk` int NOT NULL,
    FOREIGN KEY(`license_status_fk`) REFERENCES `license_status` (`id`)
);

CREATE INDEX `license_status_fk_index` on `event` (`license_status_fk`);

CREATE TABLE `publication` (
    `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `uuid` varchar(255) NOT NULL,	/* == content id */
    `title` varchar(255) NOT NULL,
    `status` varchar(255) NOT NULL
) ROW_FORMAT=DYNAMIC;

CREATE INDEX uuid_index ON publication (`uuid`);

CREATE TABLE `user` (
    `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `uuid` varchar(255) NOT NULL,
    `name` varchar(64) NOT NULL,
    `email` varchar(64) NOT NULL,
    `password` varchar(64) NOT NULL,
    `hint` varchar(64) NOT NULL
) ROW_FORMAT=DYNAMIC;

CREATE TABLE `purchase` (
    `id` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `uuid` varchar(255) NOT NULL,
    `publication_id` int(11) NOT NULL,
    `user_id` int(11) NOT NULL,
    `license_uuid` varchar(255) NULL,
    `type` varchar(32) NOT NULL,
    `transaction_date` datetime,
    `start_date` datetime,
    `end_date` datetime,
    `status` varchar(255) NOT NULL,
    FOREIGN KEY (`publication_id`) REFERENCES `publication` (`id`),
    FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ROW_FORMAT=DYNAMIC;

CREATE INDEX `idx_purchase` ON `purchase` (`license_uuid`);

CREATE TABLE `license_view` (
    `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `uuid` varchar(255) NOT NULL,
    `device_count` int(11) NOT NULL,
    `status` varchar(255) NOT NULL,
    `message` varchar(255) NOT NULL
) ROW_FORMAT=DYNAMIC;

Apart from this julianday is missing in my dbms:
DELIMITER $$
CREATE FUNCTION julianday (x1 datetime)
RETURNS integer
DETERMINISTIC
BEGIN 
  DECLARE ret integer;
  select TO_DAYS(x1)+1721060 into ret;
  RETURN ret;
END$$
DELIMITER ;

and I've fixed a couple of "[publication]" string in frontend source code

**Comment by llemeurfr** [comment]
Thanks a lot for the feed back @giancanuz . Do you think we should directly update the proposed MySQL script in dbmodel/mysql db seyup.sql?

**Comment by giancanuz** [comment]
@llemeurfr shortly: dont think so considering:

- newer version of mysql are not affected by large primary key issues since they reserved 3072 bytes instead of 767 and therefore current script should work. I am assuming here database charset is set to "utf8mb4"

- julianday function is just a dummy example in order to make dashboard loads some content

maybe you can consider:
- AUTO INCREMENT on int(11) primary keys is always a good idea. 
in source code:
- find and replace "[publication]" => "publication"
- find and replace "as bit" => "as int"

**Comment by llemeurfr** [comment]
Fixed via a set of commits in March 2020
