### ISSUE TITLE
Can you give me a complete lcp server deployment tutorial

### ISSUE THREAD

**Issue by wtfshine** [readium/readium-lcp-server#172]
Can you give me a complete lcp server deployment tutorial

**Comment by llemeurfr** [comment]
After you've read the README and the Wiki of the project, can you please detail which information is missing (installation? setup? API?) we'll then complete the guides.

**Comment by blessedmadukoma** [comment]
The API, depoying the LCP server to Heroku, that is where I have issues, I believe I have to use .env files, but the lcpserver/lcpserver.go file cannot run without having the other files with it. There is no general main.go file
