### ISSUE TITLE
Hello, readiumsdk how to access readium-lcp

### ISSUE THREAD

**Issue by wtfshine** [readium/readium-lcp-server#175]
Now that I have integrated readiumsdk, I need drm. The development documentation says that lcp-server can be integrated. Where is the specific development document?

**Comment by llemeurfr** [comment]
Information about the LCP DRM is found at https://www.edrlab.org/readium/readium-lcp/. Please read it first and checks that it's what you are looking for. Then, for more information about the open-source software provided by Readium, go to https://github.com/readium/readium-lcp-client. This is a Readium LCP module for the SDK. THe server side is for license providers, not apps.
