### ISSUE TITLE
License Status Server lsdserver database

### ISSUE THREAD

**Issue by rayowens** [readium/readium-lcp-server#176]
Missing database: lsdserver  - License Status Server
Could someone please indicate how to find or create the database for the lsdserver.

The default "lsd.sqlite" does not seem to be present in the available files. The default db for lcpserver is included ('lcp.sqlite') but not for lsdserver.  I would be grateful for the information.  

The configuration I have installed was via 'go get github.com/readium/readium-lcp-server'

**Comment by llemeurfr** [comment]
If the config contains indication to use a SQLite db, the tables are created automatically. Check the database property in the README. If you want to use another DB, you'll find in the repo (dbmodel) creation scripts for MySQL and I know of a company which has ported it for SQLServer (I'll try to get their table creation scripts); the config property must be set accordingly. The scripts are creating tables for the LCP, LSD and Frontend servers in the same DB. If you prefer to split your install in different DBs, it's easy to customize the scripts.  

Note that we're on the verge of merging in the develop branch an important evolution, as we move to Gorm, a Go Object Relational mapper, for being able to handle more DB types.  For the short term you can use the master branch without problem.

**Comment by rayowens** [comment]
Thank you, I do indeed want to use the standard SQLite.  

 

I had also used your .yaml recommendations, which seemed to point to three different databases for lcpserver (lcp.sqlite), lsdserver (lsd.sqlite), and frontend (frontend.sqlite).  The lcpserver db is present, and it launches properly.  But the other two are not present, and I cannot launch lsdserver, hence my puzzle.

 

I had checked the dbmodel repo and it seemed to be only for a single database.  Should there be three different databases ? Or have I misunderstood, and the three modules use the same database ?  Grateful for your help.   Ray

 

De : L. Le Meur [mailto:notifications@github.com] 
Envoyé : lundi 4 juin 2018 13:10
À : readium/readium-lcp-server <readium-lcp-server@noreply.github.com>
Cc : rayowens <ray.owens@orange.fr>; Author <author@noreply.github.com>
Objet : Re: [readium/readium-lcp-server] License Status Server lsdserver database (#176)

 

If the config contains indication to use a SQLite db, the tables are created automatically. Check the database property in the README. If you want to use another DB, you'll find in the repo (dbmodel) creation scripts for MySQL and I know of a company which has ported it for SQLServer (I'll try to get their table creation scripts); the config property must be set accordingly. The scripts are creating tables for the LCP, LSD and Frontend servers in the same DB. If you prefer to split your install in different DBs, it's easy to customize the scripts.

Note that we're on the verge of merging in the develop branch an important evolution, as we move to Gorm, a Go Object Relational mapper, for being able to handle more DB types. For the short term you can use the master branch without problem.

**Comment by llemeurfr** [comment]
You're right, my sample is using 3 different SQLite DBs, for making clear that this is possible and allows you to install each server on a different system platform. The sample scripts are more basic and install everything in the same DB.  It makes no difference when you run the app. Equally, you can either create one configuration file per server app or a single configuration file for all of them. 

For your tests, the simplest is to use one host system, one configuration file and 3 SQLite DB files.
