### ISSUE TITLE
Large EPUB file doesn't load, timeout

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#177]
When loading a large encrypted file (e.g. cc-shared-culture.epub, 34 Mb), the http GET goes in timeout after 15 sc. 

The http.server timeout is set in lcpserver/server/server.go (l.82) -> WriteTimeout. It is set to 15 * time.Second in the codebase. 
A change to 240 * time.Second doesn't change the fact that a timeout occurs after 4 mn. 

The code that sends bytes on the http response socket is in lcpserver/store.go (l.257). It is 

```
contentReadCloser, err := item.Contents()
defer contentReadCloser.Close()
...
io.Copy(w, contentReadCloser)
```

It may well be the culprit.

**Comment by danielweck** [comment]
https://github.com/readium/readium-lcp-server/blob/develop/lcpserver/api/store.go#L245-L257

https://github.com/readium/readium-lcp-server/blob/b713864c2dcd73d9f643d2c2e31e4961b9dafdcf/lcpserver/api/store.go#L245-L257

**Comment by danielweck** [comment]
https://github.com/readium/readium-lcp-server/blob/develop/lcpserver/server/server.go#L82-L83
https://github.com/readium/readium-lcp-server/blob/b713864c2dcd73d9f643d2c2e31e4961b9dafdcf/lcpserver/server/server.go#L82-L83

**Comment by danielweck** [comment]
Note that generally-speaking, `io.Copy(dest, src)` buffers / streams data into the HTTP response body, so this should work just fine.

Perhaps `contentReadCloser, err := item.Contents()` is a data source that does not provide efficient buffering?

Interface:

https://github.com/readium/readium-lcp-server/blob/develop/storage/interface.go#L40
https://github.com/readium/readium-lcp-server/blob/b713864c2dcd73d9f643d2c2e31e4961b9dafdcf/storage/interface.go#L40

Filesystem implementation:

https://github.com/readium/readium-lcp-server/blob/develop/storage/fs.go#L54-L57
https://github.com/readium/readium-lcp-server/blob/b713864c2dcd73d9f643d2c2e31e4961b9dafdcf/storage/fs.go#L54-L57


...or maybe the HTTP client does not pipe the response fast enough into its data sink? (e.g. downloaded file)
