### ISSUE TITLE
partial license, Encryption.UserKey.Value, implicit base64 due to Go JSON marshal

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#179]
With partial license passed in HTTP POST request, `Encryption.UserKey.Value` is implicitly base64-encoded, yet documentation says to use the hexadecimal string representation of the SHA256 byte array.
See:
https://github.com/readium/readium-lcp-server/wiki/License-Server

Go JSON encoder/decoder (marshalling):
https://golang.org/pkg/encoding/json/
"[]byte encodes as a base64-encoded string"

`Encryption.UserKey.Value`:
https://github.com/readium/readium-lcp-server/blob/develop/license/license.go#L40

**Comment by danielweck** [comment]
Option 1): patch the JSON encoder/decoder code to handle byte arrays via their hexadecimal encoding.
Maybe define a subtype of `[]byte` and implement the (un)marshall interfaces?
```go
type MyByteArray []byte

func (mba MyByteArray) MarshalText() (text []byte, err error) {
   return mba[:], nil
}

func (mba *MyByteArray) UnmarshalText(text []byte) error {
   *mba = text[:]

   return nil
}
```

```go
type UserKey struct {
...
    Value MyByteArray `json:"value,omitempty"`
}
```

**Comment by danielweck** [comment]
Option 2): change the server documentation to use base64 encoding of the hexadecimal representation of the sha256 byte array (user key passed via `Encryption.UserKey.Value`)

**Comment by danielweck** [comment]
Personally, I have a preference for option (2) because base64 is used everywhere else (consistency). In practice, base64 is in fact already used for `Encryption.UserKey.Value` by the component that issues POST requests with the partial license payload, so there should not be breaking / regression bugs in the existing Readium LCP server implementation, only changes in the specification / documentation (and maybe third-party implementations?).

**Comment by miendinh** [comment]
hi @danielweck 

thanks for your reply,

I follow your option (2) recommendation, I use base64 to encode sha256.
but I still get error result after updating partial license:

```
{
    "title": "Internal Server Error",
    "status": 500,
    "detail": "crypto/aes: invalid key size 64"
}
```

This is my partial license information:

Firstly, I base64 user passphrase:
clear text: `1234567890`
sha256(clear text): `c775e7b757ede630cd0aa1113bd102661ab38829ca52a6422ab782862f268646`
base64(sha256): `Yzc3NWU3Yjc1N2VkZTYzMGNkMGFhMTExM2JkMTAyNjYxYWIzODgyOWNhNTJhNjQyMmFiNzgyODYyZjI2ODY0Ng==`

So, my partial license is : 
```
{
  "provider": "https://www.edrlab.org",
  "encryption": {
    "profile": "http://readium.org/lcp/basic-profile",
    "user_key": {
 "algorithm": "http://www.w3.org/2001/04/xmlenc#sha256",
   "text_hint": "hint",
   "value": "Yzc3NWU3Yjc1N2VkZTYzMGNkMGFhMTExM2JkMTAyNjYxYWIzODgyOWNhNTJhNjQyMmFiNzgyODYyZjI2ODY0Ng=="
    }
  },
  "user": {
    "id": "3a92c446-d5bb-4e25-95f8-aa3833f4d68b",
    "email": "81DBEe7Y3BUofLwA5au23b0rOsIhcLx6NWLYXO3K/rw4bC0IZLz1MrPXCQtDJON9",
    "name": "y46ev69Rby4c01VHvGp91yJOuXadzXmf1zV/FV/fNmc=",
    "encrypted": [
      "email",
      "name"
    ]
  },
  "rights": {
    "print": 10,
    "copy": 2000
  }
}
```

**Comment by danielweck** [comment]
Mhmm, the AES-256-CBC cypher uses a 32-bytes / 256-bits key (64 characters when hex-encoded), so the SHA256 hash digest should work just fine once the base64 string is decoded.

What Git revision / branch are you using? (or what existing server deployment URL are you using when issuing PostMan POST HTTP requests?)

If I am not mistaken, the "official" EDRLab test servers are built from the `develop` branch, and this is the code that creates the HTTP requests with the "partial license" payload that contains the serialized `Encryption.UserKey.Value` byte array (implicit base64 of hex-encoded binary buffer):
https://github.com/readium/readium-lcp-server/blob/develop/frontend/webpurchase/webpurchase.go#L207

**Comment by miendinh** [comment]
Hi @danielweck , 

I use master branch, setup lcp on my local and make POST call to lcpserver directly
( POST <LCPbaseURL>/licenses/<license_id>/publication )

after debugging, I realize that the bug seems to occur in converting from JSON payload partial license to 
license.Encryption.UserKey.Value process ( line 197 https://github.com/readium/readium-lcp-server/blob/master/license/license.go ) 
which has the length 48 bytes lead to my bug.

so, I devide to hard code file https://github.com/readium/readium-lcp-server/blob/master/license/user_key.go

to change userKey, err := hex.DecodeString(s) with s = sha256("1234567890")

Here is my file: user_key.go

```
import (
    "encoding/hex"
    "fmt"
    "log"
)

func GenerateUserKey(key UserKey) []byte {
    var userKey []byte
    //userKey = key.Value
    
    // sha256 of password = "1234567890"
    const s = "c775e7b757ede630cd0aa1113bd102661ab38829ca52a6422ab782862f268646"

    userKey, err := hex.DecodeString(s) // the lenght of userKey is 32 bytes, instead of 48 bytes
    if err != nil {
        log.Println(err)
    }

    log.Println("User Key here------------------" + fmt.Sprintf("%s\n", userKey));

    return userKey
}
```

after that, I make POST call to LCP server to get licenced epub and I can open it by Readium desktop with password "1234567890"

Please give me some guides to solve this issues instead of hard code.

thank you very much!

**Comment by danielweck** [comment]
At this stage I would suggest using the `develop` branch due to the following changes compared with `master`:
https://github.com/readium/readium-lcp-server/compare/master...develop

**Comment by miendinh** [comment]
Many thanks to @jpbougie @danielweck 

Base on your guides, my issue is solved.
I'm so appreciated. 
Here is my function to generate encryption.user_key.value for partial license.

```
package main

import (
	"crypto/sha256"
	"encoding/base64"
	"reflect"
	"fmt"
)

func main() {
	clearText := "1234567890"
	
	//step 1: apply sha256
	hash := sha256.New()
	hash.Write([]byte(clearText))
	password := hash.Sum(nil)	

	fmt.Println(reflect.TypeOf(password))
	fmt.Println(password)

	//step 2: base64
	base64Password := base64.StdEncoding.EncodeToString(password)
	fmt.Println(base64Password) // x3Xnt1ft5jDNCqERO9ECZhqziCnKUqZCKreChi8mhkY=
}
```

**Comment by danielweck** [comment]
Great :)
Conclusion: we need to fix the documentation:
https://github.com/readium/readium-lcp-server/wiki/License-Server
...where the provided example `"value": "2f9beffa3d2b524d3ace53410177e924e640bf83b002099b6802634cd0f04d70"` (JSON `Encryption.UserKey.Value` property) should instead be the correct Base64 representation of the 32-bytes / 256-bits binary buffer corresponding to the SHA256 hash (not the 64-characters hexadecimal digest, but the raw byte array) of the plaintext arbitrary user passphrase.

The actual documentation text currently is:

> value: a custom json property added to the partial license. Warning: it is not part of the LCP specification. It contains the hashed value of the user passphrase in hexadecimal string format (i.e. 64 bytes as long as the sha256 algorithm is used by the encryption profile).

@llemeurfr what do you think?

**Comment by jpbougie** [comment]
In addition to the documentation fix, we could trap the error from crypto/aes and translate it to something a bit more useful for the user

**Comment by llemeurfr** [comment]
We'll fix the documentation first, and then add an alternative value containing, as a string the simple hash (hex encoded as usual). The server will convert it to a byte[].

**Comment by llemeurfr** [comment]
For the record, here is a PHP sample offered by ePagine (fr) to convert the hex-encoded sha value to a byte array:

```
                function convertHexStringToByteArray($string)
                {
                               $outArray = array();
                               for($i=0;$i < strlen($string)/2;$i++)
                               {
                                               $tmp = substr($string,$i*2,2); // get 2 chars
                                               $tmp2 = base_convert($tmp,16,10); // Convert to base 10
                                               $outArray[] = (int)$tmp2; 
                               }
               
                               return $outArray;
                }
```

**Comment by llemeurfr** [comment]
The LCP Server doc has been updated. Now we have to make a (backward compatible) evolution on the code to simplify the use of this parameter for newcomers, plus - if not too complex - trap the error from crypto/aes and translate it to something a bit more useful for developers.

**Comment by llemeurfr** [comment]
The develop branch of the LCP Server has been updated. Please read the updated documentation in the Wiki, and use 'hex_value' (hex encoded value of the passphrase hash) instead of 'value' (formatted as explained above) **if you wish**. **Backward compatibility is guaranteed**.
