### ISSUE TITLE
Frontend license_link_url

### ISSUE THREAD

**Issue by leomoty** [readium/readium-lcp-server#183]
While testing with `r2-testapp-js`, I got this, I was trying to revoke a license and then open the epub again.

```
r2:lcp#lsd/lcpl-update LSD license updating... +0ms
  r2:lcp#lsd/lcpl-update OLD LCP LICENSE, FETCHING LSD UPDATE ... http://192.168.10.97:8991/api/v1/licenses/licenses/8eb12f09-8426-41d2-b27d-d9368c2c3fb2 +1ms
  r2:lcp#lsd/lcpl-update content-type => application/problem+json +19ms
  r2:lcp#lsd/lcpl-update vary => Origin +0ms
  r2:lcp#lsd/lcpl-update x-content-type-options => nosniff +1ms
  r2:lcp#lsd/lcpl-update date => Thu, 16 Aug 2018 16:52:47 GMT +0ms
  r2:lcp#lsd/lcpl-update content-length => 35 +2ms
  r2:lcp#lsd/lcpl-update connection => close +0ms
  r2:lcp#lsd/status-document-processing HTTP CODE 404 +27ms
  r2:lcp#lsd/status-document-processing What?! LSD revoked +0ms
  r2:testapp#electron/main/index launchStatusDocumentProcessing DONE. +51ms
(node:7595) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 404 - "{\"title\":\"Not Found\",\"status\":404}\n"
(node:7595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am pretty sure my license link URL is wrong: http://192.168.10.97:8991/api/v1/licenses/licenses/8eb12f09-8426-41d2-b27d-d9368c2c3fb2.

However, the `frontend` doesnt seem to resolve the http://192.168.10.97:8991/licenses/8eb12f09-8426-41d2-b27d-d9368c2c3fb2 either.

**Comment by danielweck** [comment]
The message `HTTP CODE 404` comes from:
https://github.com/edrlab/r2-lcp-js/blob/79da797b57c2579ee9c7a214d1550021db7e51bc/src/lsd/lcpl-update.ts#L69

It looks like your URL:
`http://192.168.10.97:8991/api/v1/licenses/licenses/8eb12f09-8426-41d2-b27d-d9368c2c3fb2`
should be:
`http://192.168.10.97:8991/api/v1/purchases/licenses/8eb12f09-8426-41d2-b27d-d9368c2c3fb2`
?

**Comment by leomoty** [comment]
This is what the README has:

```
lsd:
    license_link_url: "http://127.0.0.1:8991/licenses/{license_id}"
```

While mine is wrong, `/licenses/{license_id}` nor `/purchases/licenses/{license_id}`  seems to work.

**Comment by danielweck** [comment]
Okay, thanks for the rapid feedback. Sorry I am not able to help on this occasion (like I mentioned in the other issue, it has been a while since I tinkered with local instances of LCP/LSD/frontend servers, and the `config.yaml` settings).
@llemeurfr what do you think?
@leomoty what Git revision / branch are you using to build the Go code?

**Comment by llemeurfr** [comment]
You should have     license_link_url: "http://192.168.x.y:8991/api/v1/licenses/{license_id}",

see [the Wiki](/readium/readium-lcp-server/wiki/Test-frontend-server#fetch-an-existing-license) for more info.

I just corrected the readme on the develop branch.

**Comment by leomoty** [comment]
Thank you @llemeurfr.
