### ISSUE TITLE
lcpserver PUT contents/{content_id} duplicate encrypted file

### ISSUE THREAD

**Issue by tgachet** [readium/readium-lcp-server#184]
Hello,

When adding the content to the storage, the encrypted file (output by lcpencrypt) is copied (contenId, no extension) and sent to the file storage endpoint.
**func AddContent, store.go**
```
// add the file to the storage, named from contentID
_, err = s.Store().Add(contentID, file)
```

This file is the only that matters for LCPServer. The original mybook.lcp.epub file can be deleted as it has no use.

It would be nice to keep that "storage" functionality as it's the only way to use an s3 bucket but find a way not to keep twice the same file.

Example :
**config.yml**
```
storage:
    filesystem:
        directory: "~/files/lcp"
```
**Encryption**
`lcpencrypt --input "~/files/mybook.epub" --contentid mybook --output "~/files/mybook.lcp.epub" --lcpsv "http://lcp:8989" --login "lcp" --password "pass"`

**FS**
```
~/files/mybook.epub ##### original file
~/files/mybook (or s3bucket if used with s3 mode) ###### encrypted file
~/files/lcp/mybook.lcp.epub ###### unused file
```
Thank you

**Comment by llemeurfr** [comment]
Solved by fc693c43b7146ab9850b8e864436e7812fae06f6
