### ISSUE TITLE
lcpencrypt, regression after update to go 1.11

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#185]
After upgrade to go 1.11, encryptions return an error on most EPUB files. 

The exact error is in aes_cbc.go / Encrypt(), but the reason why it breaks is that it tries to encrypt a directory (OEBPS/). 

In pack.go / DO(), in the loop on all EPUB Resources (~l.50), we can see that the code processes META-INF, META-INF/container.xml, then OEBPS,  OEBPS/*.xhtml. 
canEncrypt() on OEBPS/ returns true (and the other condition is also true), therefore encryptFile() is called, which calls the aes Encrypt() function. too bad. 

canEncrypt() returns true because OEBPS/ is in the list of resources prepared in epub/reader.go, Read() function; but not in the white list (cleartextResources) checked by canEncrypt().

**Comment by llemeurfr** [comment]
My take is that OEBPS should not be in the list of resources; I wonder if the zip reader in reader.go Read() does not find directories via `for _, file := range r.File` where it didn't find them before (but I may be wrong).

**Comment by danielweck** [comment]
Ah, this reminds me of an issue with a Node implementation of filesystem "globs", which impacted various file / folder utilities that depended on it.

So is this a regression bug with the Go `archive/zip` API? Or something to do with our code?

API doc:
https://golang.org/pkg/archive/zip/#FileHeader
> A trailing slash indicates that this file is a directory and should have no data.

There have been Go changes related to the `archive/zip` package, but nothing looks suspicious:
https://golang.org/doc/devel/release.html
https://github.com/golang/go/commits/master/src/archive/zip/reader.go

Related issue?
https://github.com/golang/go/issues/24082
(all "zip" issues: https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+zip )

Code reference:
https://github.com/readium/readium-lcp-server/blob/43ceda732a2d5fd36180a087b246859d7aa96ca5/epub/reader.go#L143
( https://github.com/readium/readium-lcp-server/blob/master/epub/reader.go#L143 )

**Comment by llemeurfr** [comment]
Solved by #187
