### ISSUE TITLE
FilterLicenseStatuses devices = 0

### ISSUE THREAD

**Issue by xabierXercode** [readium/readium-lcp-server#194]
Because the call <LSDbaseURL> / licenses {? Devices, page, per_page} the devices parameter, must be greater than 0?
Is there any restriction on the specification? I do not see it

I would like to filter the licenses that are not assigned to any device

**Comment by llemeurfr** [comment]
The FilterLicenseStatuses was programmed to detect oversharing -> licenses for which the device count is greater than the device limit. 

A filter (> 0) is also set in https://github.com/readium/readium-lcp-server/blob/master/lsdserver/api/license_status.go#L570.

Filtering licenses no assigned to any device (= unused) will need an additional REST method.

**Comment by xabierXercode** [comment]
Ok thanks
