### ISSUE TITLE
EPUB covers and ncx should never be encrypted

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#197]
In https://github.com/readium/readium-lcp-server/blob/master/epub/epub.go#L38 
and
https://github.com/readium/readium-lcp-server/blob/master/epub/reader.go#L160
we see how the cover is detected. 

The EPUB 2 way is explained e.g. in http://jiminy.chapalpanoz.com/retrocompatibilite-epub3/ 
We must be able to detect a cover from 
&lt;meta name="cover" content="cover-id" />, cover-id being the id of the manifest item representing the cover. 

It seems it does not work properly yet.

**Comment by danielweck** [comment]
This is already implemented:
https://github.com/readium/readium-lcp-server/blob/66d2a9adeffa7e1e24b4d56476ccd3ed58c6cf0e/epub/reader.go#L160-L181

**Comment by llemeurfr** [comment]
If fact the issue was appearing when the resources were in the root path of the EPUB. 
The list of "clear" resources was set with paths like "./file-name" where it was later searched via path like "file-name" in epub.go / CanEncrypt(), called from https://github.com/readium/readium-lcp-server/blob/master/pack/pack.go#L37.

**Comment by llemeurfr** [comment]
fixed via fbfe789454051f78c99f7958d1d40cb656708d6b

**Comment by danielweck** [comment]
Ah, well spotted!
What about this line?
https://github.com/readium/readium-lcp-server/blob/fbfe789454051f78c99f7958d1d40cb656708d6b/epub/reader.go#L190
(should also check for `.`?)

**Comment by llemeurfr** [comment]
filepath.Rel() does the work properly, no "./" added. Reading this part of the code, I discovered filepath.ToSlash(), which is cleaner for changing backslashes to slashes on Windows. I'll make a new fix using this instead of string concatenation.

**Comment by llemeurfr** [comment]
clean via 7f4124e65774943e6ea2f4085766baafc441c3ef
