### ISSUE TITLE
MySQL rejects zero dates

### ISSUE THREAD

**Issue by jrsupplee** [readium/readium-lcp-server#204]
The current code sends a zeroed date ('0000-00-00') for `potential_rights_end` if none was specified.  MySQL fails.  The code needs to send a NULL rather than a zeroed date.

Affected file `license_statuses/licence_statuses.go`.  `Add` method.

**Comment by jrsupplee** [comment]
Here's my new add method:

	func (i dbLicenseStatuses) Add(ls LicenseStatus) error {
		add, err := i.db.Prepare("INSERT INTO license_status (status, license_updated, status_updated, device_count, potential_rights_end, license_ref,  rights_end) VALUES (?, ?, ?, ?, ?, ?, ?)")
		if err != nil {
			return err
		}
		defer add.Close()
	
		statusDB, err := status.SetStatus(ls.Status)
	
		if err == nil {
			var end *time.Time
			end = nil
			if ls.PotentialRights != nil && ls.PotentialRights.End != nil && !(*ls.PotentialRights.End).IsZero() {
				end = ls.PotentialRights.End
			}
			_, err = add.Exec(statusDB, ls.Updated.License, ls.Updated.Status, ls.DeviceCount, end, ls.LicenseRef, ls.CurrentEndLicense)
		}
	
		return err
	}

**Comment by jrsupplee** [comment]
I added a pull request.

**Comment by llemeurfr** [comment]
Solved via 50d68c0e35ba25b986f382e6427ea3d863d7ef57
