### ISSUE TITLE
Send a notification from lcpencrypt to the frontend? 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#206]
when lcpencrypts does its job, it sends a notification to the lcpserver (if you set the proper parameters), the lcpserver notifies the lsdserver, but does not notify the frontend server. So you don't see in the frontend UI a publication processed via lcpencrypt. The rationale is that implementers use lcpencrypt as part of their ingest process and integrate it with their own frontend service; the test frontend we provide is just ... a testing tool. 

But it could be worth adding a notification from lcpencrypt to the test frontend to make the standard workflow more obvious.

**Comment by jjbier** [comment]
This is a very interesting feature.
I would like to know when you plan to add this feature?
How can I help you implement it?

**Comment by llemeurfr** [comment]
Well it's not a real priority for me, as the Test Frontend has its own EPUB encryption facility on upload. 

But I should be able to work on it during the fall, at the time I work on a refactoring of the Test Frontend (it is too complex now with its mix of golang and angular / ts / node modules).

What would be your use of it?

**Comment by jjbier** [comment]
Sorry I misunderstood the functionality. The notification would not be from lcpencrypt to fronted, but from Status server to fronted.

I'll tell you about the use case, in case you can give me an idea.
If a user returns or renews a book from an App, I must notify an external circulation service.
I have two alternatives:
1st Mofit the Status server service, to carry out this notification.
2º Put a service on top of the Status server, and that this is the one that makes notifications to the Status server and the external circulation service.

**Comment by llemeurfr** [comment]
It appears that most implementers setup the following to control loan extensions, and that could be used for early returns also: 

- configure the Status Server so that the renew/return public URLs point to an external circulation service
- let the circulation service decide if the loan extension is approved (can depend on the waiting queue or any other principle)
- if approved, the circulation service calls the LSD server internally

Using such proxy service for making the circulation manager aware of early return before the request is passed to the LSD server is also possible. 

Isn't it a better solution?

**Comment by jjbier** [comment]
Changing the url of the Server status is a better solution.
Thanks for your help.
