### ISSUE TITLE
Allow re-encrypting content with the same content id

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#211]
From Turgay: "when we try to update existing content with  lcpencrypt, even if the lcpserver is notified and returns a 200 OK, the db fields are not modified with the new encryption key, rendering subsequent decryption of the content impossible."

**Comment by llemeurfr** [comment]
The use case seems to be re-encrypting content with a given content id (-contentid set in lcpencrypt).

**Comment by tbirand** [comment]
To further clarify this, note that the encrypted file on the file system does get updated with the new one, but the checksum and encryption key in the db remain out of date which is likely why subsequent fulfillments fail. This would prevent a provider from being able to seamlessly update editions of a book to enable re-downloads of updated content.

**Comment by tbirand** [comment]
Fix here: https://github.com/readium/readium-lcp-server/pull/213

**Comment by llemeurfr** [comment]
Fix applied.
