### ISSUE TITLE
When license is revoked from server, LSD exposes renew/return links even for "BUY" (not "LOAN") purchases

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#226]
"BUY" purchase from server front end:

<img width="826" alt="Screenshot 2020-09-15 at 07 38 28" src="https://user-images.githubusercontent.com/625201/93174938-c7230380-f726-11ea-8f1a-b882ae54a645.png">

**Comment by danielweck** [comment]
Revoked from server front end:
<img width="334" alt="Screenshot 2020-09-15 at 07 38 53" src="https://user-images.githubusercontent.com/625201/93174983-dc982d80-f726-11ea-9178-4361b348e709.png">

**Comment by danielweck** [comment]
Note the added renew and return links (exposed in LSD since the license revocation):

<img width="970" alt="Screenshot 2020-09-15 at 07 39 11" src="https://user-images.githubusercontent.com/625201/93175039-f20d5780-f726-11ea-9d50-010857e2d19f.png">

**Comment by llemeurfr** [comment]
Fixed in 0c44d835558826ad0de5596c49c9814d9b9fe463
