### ISSUE TITLE
Files are deflated post-encryption

### ISSUE THREAD

**Issue by mickael-menu** [readium/readium-lcp-server#228]
The LCP server seems to be deflating non-media files in the produced archive. This is not necessary because the deflate step was applied before encryption and doing it post-encryption shouldn't bring any difference in size (you can see it in the log below, deflated encrypted files are only reduced by 1%).

It's an issue because performing byte range requests on deflated ZIP entries is noticeably slower in reading apps. However, in practice it's probably a minor issue because non-media files are rarely really big.

```
      912  Defl:N      917  -1% 11-30-1979 00:00 68d62c21  EPUB/xhtml/p40.xhtml
      368  Defl:N      373  -1% 11-30-1979 00:00 0b066924  EPUB/xhtml/cover.xhtml
     1056  Defl:N     1061  -1% 11-30-1979 00:00 4b954c6e  EPUB/xhtml/p20.xhtml
  3265184  Stored  3265184   0% 11-30-1979 00:00 35be6990  EPUB/audio/asharedculture_soundtrack.mp3
361374208  Stored 361374208   0% 11-30-1979 00:00 471d4b4b  EPUB/video/shared-culture.mp4
    19904  Defl:N      840  96% 11-30-1979 00:00 51d0d74c  META-INF/encryption.xml
     4017  Defl:N     2767  31% 09-25-2020 11:46 94fc7de3  META-INF/license.lcpl
```

**Comment by danielweck** [comment]
Seems like a bug to me. The "SHOULD" conformance requirement is unequivocal in the EPUB specification:

https://www.w3.org/publishing/epub/epub-ocf.html#sec-container-metainf-encryption.xml

> Within the ZIP directory, encrypted files SHOULD be stored rather than Deflate-compressed.

...and of course there is the pre-encryption DEFLATE vs. STORE rule, but that's not the topic of this issue (I am just mentioning it here for the sake of completion):

https://www.w3.org/publishing/epub/epub-ocf.html#sec-enc-compression

> When stored in a ZIP container, streams of data with Non-Codec content types SHOULD be compressed before they are encrypted, and Deflate compression MUST be used.
> Streams of data with Codec content types SHOULD NOT be compressed before they are encrypted.

**Comment by llemeurfr** [comment]
Agreed, the implementation is not optimized, as non-media file are deflated by the go software, then encrypted, then deflated again at the time they are added to the zip. In practice all files should be STORED at zip level. 

This impacts the EPUB zip creation and associated tests, but also the RWPP zip creation. 

It will be modified in the next version of the LCP server.
