### ISSUE TITLE
Readium LCP doesn't support RWPM .audiobook files

### ISSUE THREAD

**Issue by vbessonov** [readium/readium-lcp-server#232]
Readium LCP doesn't support RWPM .audiobook files.

[lcpencrypt.go](https://github.com/readium/readium-lcp-server/blob/master/lcpencrypt/lcpencrypt.go#L144) contains the following lines that don't contain `.audiobook` extension:
```golang
func outputExtension(sourceExt string) string {
	var targetExt string
	switch sourceExt {
	case ".epub":
		targetExt = ".epub"
	case ".pdf":
		targetExt = ".lcpdf"
	case ".lpf":
		// short term solution. We'll need to inspect the manifest and check conformsTo,
		// to be certain this is an audiobook (vs another profile of Web Publication)
		targetExt = ".audiobook"
	}
	return targetExt
}
```

Also, trying to encrypt the book using `lcpencrypt` I get the following error:
```
~/go/bin/lcpencrypt -input 9780231543975.audiobook
Error encrypting the publication; level 30
invalid argument%
```

P.S. @llemeurfr, I created this issue as a reference point in NYPL JIRA tickets.

**Comment by danielweck** [comment]
Isn't that also the case with the `.webpub` file extension for "generic" RWPM publications? (not just `.audiobook`)
I think that the PDF and LPF cases trigger special code paths in the Go server implementation (they both need special treatment, different from the processing of EPUB packages). I assume the RWPM case (generic, or audiobook) will trigger another processing method?

**Comment by llemeurfr** [comment]
This is now available via bd3501427d53705818897afaa2be03b627cdb70a.

I'll let the issue open until confirmation that the RWPP case is fully handled.

**Comment by vbessonov** [comment]
@llemeurfr, it works now, I left a comment in [SIMPLY-3183](https://jira.nypl.org/browse/SIMPLY-3183)

**Comment by llemeurfr** [comment]
great, thanks
