### ISSUE TITLE
can minio be used for s3 storage

### ISSUE THREAD

**Issue by isshwar** [readium/readium-lcp-server#241]
Hi,

I am trying to use minio as s3 storage for storage. but i am seeing the below error message. I followed instructions in the set up. Is lcp tested against any other s3 storage or only with aws and can it work with other s3 storage providers like minio?

`lcp-server               | 2021/04/15 08:38:45 {"title":"Bad Request","status":400,"detail":"RequestError: send request failed\ncaused by: Put \"http://edrlab-lcp-storage.minio:9000/6f43193d-bd96-46db-bc8c-42cc93021dc0\": dial tcp:
lookup edrlab-lcp-storage.minio on 127.0.0.11:53: no such host"}
lcp-server               | [negroni] 2021-04-15T08:38:44Z | 400 |        686.647ms | lcp-server:8989 | PUT /contents/6f43193d-bd96-46db-bc8c-42cc93021dc0`

my minio is hosted locally. 

Thanks
Eswar

**Comment by llemeurfr** [comment]
We don't have experience in minio. 
@iishwar I hope that you solved your problem.  
You may look at the instructions we wrote in https://github.com/readium/readium-lcp-server/wiki/Setting-up-an-S3-storage
