### ISSUE TITLE
Does the LCP server provide metrics?

### ISSUE THREAD

**Issue by isshwar** [readium/readium-lcp-server#245]

**Comment by isshwar** [comment]
HI Team,

I want to know if LCP servers emit any metrics on any endpoint point. The documentation doesn't say anything about this.

Thanks
Eswar

**Comment by llemeurfr** [comment]
The LCP server only provides what is described in https://github.com/readium/readium-lcp-server/wiki/LCP-Status-Server-API#check-overshared-licenses, i.e. what is necessary to check if licenses have been overshared and therefore is some of them should be revoked.
