### ISSUE TITLE
The server should not allow return on license is ready state 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#246]
Renew / return should only be accepted on active licenses (after at least one device has registered). 
It is correctly done for renew, but a return is currently accepted. 

For instance, 
https://lsd-test.edrlab.org/licenses/fb48b70f-1f27-4dd3-adc2-781321f1fa08/status
shows a status ready.

The initial constraints on the license are:
Start Date : 2021-07-07 12:50
End Date : 2021-07-30 12:50

PUT https://lsd-test.edrlab.org/licenses/fb48b70f-1f27-4dd3-adc2-781321f1fa08/status/renew?end=2021-07-25T15:47:00Z&id=11&name=testllm
returns 
```
{
    "title": "Forbidden",
    "status": 403,
    "detail": "The current license status is ready; renew forbidden"
}
```

but 
PUT https://lsd-test.edrlab.org/licenses/fb48b70f-1f27-4dd3-adc2-781321f1fa08/return?id=11,name=postman
returns 200 OK + status document with status cancelled

**Comment by jpbougie** [comment]
I'm not sure I understand the rationale for this. If a lending platform allows a user to return a license from its web interface, we could have a user who returns the license from that interface before ever activating it in an app (but after downloading the LCPL file).
