### ISSUE TITLE
Return the created object on success.

### ISSUE THREAD

**Issue by julkwel** [readium/readium-lcp-server#252]
For example : 

Actual : when publication/user/license created, the api return void.

Request : It was good if after creation, the api return the created object on success.

**Comment by llemeurfr** [comment]
Hi, the context of your request seems to be the Test Frontend (which is a testing tool, not part of the production package). 

And I suppose that your request is about functions like 
func CreatePublication(w http.ResponseWriter, r *http.Request, s IServer) {
https://github.com/readium/readium-lcp-server/blob/master/frontend/api/publication.go#L156

Such function takes its input from an http POST + a json payload (representing a publication) and return an http 201 if the publication is correctly created. What is in this case the pros of returning the json payload that was the input?
