### ISSUE TITLE
lcpencrypt does not include 'protected-content-type' when protecting a .rpf file?

### ISSUE THREAD

**Issue by benhiebert** [readium/readium-lcp-server#258]
Using lcpencrypt from v1.5.0.

For example, protecting an epub returns "protected-content-type": "application/epub+zip". I was expecting a different protected-content-type for a protected .rpf file, however the tool does not return any value for protected-content-type. Is this correct?

lcpencrypt -input Candide_test1.rpf -output Candide_test1_output.rpf

returns:
{
   "content-id": "7596f24e-d10b-41ed-b1e2-87ae07cee7fa",
   "content-encryption-key": "ifBOiff4k9mu5TiNPZ9XRil1RHHGWyk/hcw9ib34hYY=",
   "protected-content-location": "Candide_test1_output.rpf",
   "protected-content-length": 565004,
   "protected-content-sha256": "976780746829e8b85ce1e5a907fd6da0d3126819bf9864b3593e922bd1a7b0f8",
   "protected-content-disposition": "Candide_test1_output.rpf"
 }
Encryption was successful
[Candide_test1.rpf.zip](https://github.com/readium/readium-lcp-server/files/7247204/Candide_test1.rpf.zip)

**Comment by llemeurfr** [comment]
The .rpf extension was not official, and we have aligned the codebase to the official .webpub extension (see https://readium.org/webpub-manifest/packaging.html). 

The protected-content-type is now correctly generated.

Note that a PDF file in a Readium Package has .webpub as an extension, and .lcpdf as an encrypted extension, while an audiobook in a Readium Package has .audiobook as an extension, and .lcpau as an encrypted extension.

Currently on the develop branch, will be merged for V1.7.0.
https://github.com/readium/readium-lcp-server/blob/develop/encrypt/process_encrypt.go#L241
