### ISSUE TITLE
Deploying the Go readium-lcp-server to Heroku

### ISSUE THREAD

**Issue by blessedmadukoma** [readium/readium-lcp-server#265]
The API, depoying the LCP server to Heroku, that is where I have issues, I believe I have to use .env files, but the lcpserver/lcpserver.go file cannot run without having the other files with it. There is no general main.go file

_Originally posted by @blessedmadukoma in https://github.com/readium/readium-lcp-server/issues/172#issuecomment-1004420456_

**Comment by llemeurfr** [comment]
You may be interested by the following deployment documentations (but not on Heroku): 
https://wiki.lyrasis.org/display/SIM/How+LCP+works+in+SimplyE
https://github.com/amigoslibraryservices/lcp-docker
https://github.com/xercode/readium-lcp-server-docker

At EDRLab we are starting working on a Google Cloud deployment, starting with the simplest use case: deployment of the servers in Test mode.  

nb: there is one main() per server, and there are 2 servers (License Server and Status Doc Server) in the current version.

**Comment by blessedmadukoma** [comment]
Thank you, I will look at it
