### ISSUE TITLE
Add possibility to configure TLS for MySql

### ISSUE THREAD

**Issue by dozer75** [readium/readium-lcp-server#293]
Today it is recommended that connections to MySql uses TLS. Many times TLS configuration requires customizations to work like handling client certificates and CA certificates. 

MySql does apparently not have the same configuration in different environments. E.g. in Cloud environments Google Cloud requires custom settings both for client certificates and CA certificates while Azure (and from what I can read AWS) only requires CA certificates while other MySql server instances may only need client certificates. So the logic should support it all.

A few examples on how this is implemented:
- [Google Cloud](https://cloud.google.com/sql/docs/mysql/samples/cloud-sql-mysql-databasesql-sslcerts)
- [Azure](https://learn.microsoft.com/sv-se/azure/mysql/flexible-server/how-to-connect-tls-ssl#golang)

**Comment by llemeurfr** [comment]
Looking at the two different snippets, it seems difficult to see how to make this generic.  

I foresee a new set of config parameters and some switches in the codebase, in the initialization phase of each server. 

If you are interested, I can help for the structure, but as we don't use MySQL on the Cloud at EDRLab, you would need to fill the structure, test carefully and propose a PR.

**Comment by dozer75** [comment]
A bit old issue, I found a solution by skipping tls on the connectionstring which worked for me. I also discovered that you are implementing a SQL Server based solution as well, and since SQL Server is our primary SQL system I will look at the possibility to move to this instead when it is available.

**Comment by llemeurfr** [comment]
Hi @dozer75, you can already test the SQL Server connection from the main / master branch. We will version it very soon now. The readme gives indications about the connection string.
