### ISSUE TITLE
created/updated field on content table

### ISSUE THREAD

**Issue by atomotic** [readium/readium-lcp-server#296]
It happened to me a few times to replace an encrypted content, and I think could be useful a column(s) on `content` table to identify what/when changed

* `created_at` datetime
* `updated_at` datetime

What do you think about this? Better to do with stored procedures or application code?
Also i remember that the rewriting of lcp-server will use an orm

https://github.com/readium/readium-lcp-server/blob/66919df17f4724b2ea386a1bb0c174dc8d12f877/dbmodel/mysql_db_setup_lcpserver.sql#L1-L8

**Comment by llemeurfr** [comment]
mmmh this would be a breaking change for all users of the solution. I'd rather not cause to much problems to the multitude on installs at this point. 
But  you can decide to do this on your fork, for sure. 

Yes the upcoming v2 is using an ORM, each table has such admin fields, and I'm developing a full CRUD API for content management. 

Therefore I propose to close this here but retain the idea for v2.
