### ISSUE TITLE
API return result page

### ISSUE THREAD

**Issue by JK-Kim4** [readium/readium-lcp-server#319]
Hi, 

where can i get lcp and lsd server error document page?

my test request 'localhost:8989/contents/{content_id}' is return 401 status, but page description([https://readium.org/license-status-document/error/unauthorized](https://readium.org/license-status-document/error/unauthorized)) is not found

**Comment by llemeurfr** [comment]
Hi, 

As a general remark, there is not Web page corresponding to the different problem types. Problem type URIs are defined in the [License Status Document Specification](https://readium.org/lcp-specs/releases/lsd/latest). 
This specification is using the [RFC7807](https://datatracker.ietf.org/doc/html/rfc7807) for expressing Problems in JSON. 
Problem types are essentially used to identify problems in a unique way. 
The RFC7807 recommends that type URIs are dereferencable using an HTML page, but it does not require it.
But we (Readium folks) didn't create these pages. 

For you specific case, the 'localhost:8989/contents/{content_id}' is public and does not require authentication, therefore I don't understand how you can see this URI appearing (URI that is not defined in the codebase it seems).
