### ISSUE TITLE
lcpencrypt notify parameter clarification

### ISSUE THREAD

**Issue by Dunnymeister** [readium/readium-lcp-server#324]
The command line tool `lcpencrypt` accepts a command line parameter "notify":

```
[-notify]     optional, URL, notification endpoint for the PubStore or License server v2
```

I tried setting the value of this parameter to the URL the `lcpserver` was running under, but the notify command issued by lcpencrypt returns a 404 error after processing:

```
[negroni] 2023-09-18T10:59:08+08:00 | 404 |      710µs | 127.0.0.1:8989 | POST /publications/
2023/09/18 11:02:18 {"type":"http://readium.org/license-status-document/error/notfound","title":"Failed to find the license ID","status":404}
```
I could not see a way to obtain the LSD Server version number via the `lsdserver` command so I am unable to tell if this parameter is supported.

1. Is there a way to determine the version of `lcpserver`?
2. Can `lcpencrypt` be updated to exit on error when the `notify` parameter returns a 404, or better yet, a code other than 2XX?

It's worth noting that although the `lcpsever` returned a 404, `lcpencrypt` exited with a success status code. I was expecting an error to be returned in this case.

Ultimately, using the v1 parameters did work successfully so I was able to proceed using those.

**Comment by llemeurfr** [comment]
Thanks for the comment. This `-notify` parameter is now intended to notify the Content Management System setup by the provider of a new encryption. It sends a JSON payload which describes the publication (uuid, title, content type, description, date published, coverUrl, language(s), publisher(s), author(s) and categories).

Notification of the LCP Server is done using the `-lcpsv` parameter. 

Note: The LCP Server v2 in currently in beta version and developed on the EDRLab Github space. This v1.x will continue being maintained for at least 2 years from now.
