### ISSUE TITLE
Reading LCPL Files in a Web-Based Environment

### ISSUE THREAD

**Issue by robyfirnandoyusuf** [readium/readium-lcp-server#328]
Hello,

I'm new to Readium and am currently working on a project where I need to protect various media types, including EPUB, PDF, video, and audio files. These media files are intended to be accessed via a web-based platform. Someone told me that Readium might be the solution I'm looking for.

Here's what I've done so far with the LCP servers:

1. I encrypted my EPUB file using the following command:
```bash
./lcpencrypt -input "sample1.epub" -lcpsv "http://127.0.0.1:8989" -login "sepuh" -password 'sungkem123'
```
(Note: This notifies the LCP server.)

2. Then, I generated a license using:
```bash
curl -X POST -u sepuh:sungkem123 --header "Content-Type:application/json" \
-d '{
    "provider": "http://www.imaginaryebookretailer.com",
    "user": {
        "id": "dcb4adeb-fd82-4c16-9849-c269c12f1ae9",
        "email": "user@gtg.com",
        "kode_materi": 31337,
        "encrypted": [
            "email"
        ]
    },
    "encryption": {
        "user_key": {
            "text_hint": "The title of the first book you ever read",
            "hex_value": "4981AA0A50D563040519E9032B5D74367B1D129E239A1BA82667A57333866494"
        }
    },
    "rights": {
        "print": 1,
        "copy": 0
    }
}' \
-o puhsepuh.lcpl -J -v -D - http://127.0.0.1:8989/contents/85a08284-f44d-4094-9c9d-e2ca6fdc7716/licenses
```

3. I tested the resulting **.lcpl** file with Thorium, and it worked perfectly.

Given the above, I have a couple of questions:
1. How can I read the .lcpl file in a web-based environment?
2. How can I use Readium to handle other media types such as video, audio, and PDF files?

I would greatly appreciate any guidance or assistance. Thank you in advance!

**Comment by llemeurfr** [comment]
Hi, 

This is explained in https://www.edrlab.org/readium-lcp/faq/, Question "s Readium LCP available for Web applications?"

The short answer is that you cannot securely use LCP, or any other DRM, in a web environment. The issue is not about software, it is about security. Conceptually, the security of a DRM is based on obscurity. There must be a secret algorithm that provides some content decryption key. But in a browser, nothing is secret.  

All you could do is process the user passphrase server-side, develop a middleware able to decrypt publications resources on the fly, and use a token based approach to protect access to this content. But the content will then be in clear server side, and publishers won't be happy.

**Comment by robyfirnandoyusuf** [comment]
> Hi,
> 
> This is explained in https://www.edrlab.org/readium-lcp/faq/, Question "s Readium LCP available for Web applications?"
> 
> The short answer is that you cannot securely use LCP, or any other DRM, in a web environment. The issue is not about software, it is about security. Conceptually, the security of a DRM is based on obscurity. There must be a secret algorithm that provides some content decryption key. But in a browser, nothing is secret.
> 
> All you could do is process the user passphrase server-side, develop a middleware able to decrypt publications resources on the fly, and use a token based approach to protect access to this content. But the content will then be in clear server side, and publishers won't be happy.

ooh, what about this tool? is it can read the encrypted epub file?
https://github.com/readium/r2-streamer-js/

**Comment by llemeurfr** [comment]
This r2-streamer-js could be part of the solution I was describing, but if you start such a development, you'll have to add lots of code to obtain what you want.
