### ISSUE TITLE
Add a "self" relation to license status documents

### ISSUE THREAD

**Issue by jotson** [readium/readium-lcp-server#338]
Is it possible to add a "self" relation to license status documents? Something like this in `license_status.go:makeLinks()`:

```golang
link := licensestatuses.Link{Href: lsdBaseURL + "/licenses/" + ls.LicenseRef + "/status", Rel: "self", Type: api.ContentType_LSD_JSON, Templated: false}
*links = append(*links, link)
```

If you're willing, I can submit a PR. Please let me know if you have any special requirements for it.

**Background:**

We're doing an OPDS2+ODL[^1] implementation with LCP for library lending.

When a client performs a "checkout" we ask the lcp server to generate a new license. The ODL spec requires the response to a "checkout" to be a License Status Document. Our problem is that the License Status Document doesn't link to itself so there's no way for the client to query the status again in the future.

[^1]: https://drafts.opds.io/odl-1.0.html

**Comment by llemeurfr** [comment]
The requirement comes from https://drafts.opds.io/odl-1.0.html#54-interacting-with-a-checkout-link and https://drafts.opds.io/odl-1.0.html#54-status-of-a-checkout (note the double 5.4; should be corrected in the ODL spec). 

I suppose that when an ODL client sends a Checkout command to an ODL Server, the ODL Server requests a License generation from the LCP Server, does not care about the License returned at this point, gets the License Status Document from the LCP Server (using the link in the License), and returns it to the ODL client.  
(I'm wondering why the License is not returned directly, but this is not the point here; I'll discuss that with the ODL people.)

I'll discuss with the LCP people a light evolution of the LCP specification itself, to explicitly introduce this self link. Knowing the type of algorithm used for link retrieval, client software will not be impacted by the introduction of a new link in License Status Documents.
