### ISSUE TITLE
Add health probe endpoints to lcpserver and lsdserver

### ISSUE THREAD

**Issue by jbauerrfid** [readium/readium-lcp-server#339]
It would be helpful to have health status endpoints in lcpserver and lsdserver

**Ping endpoint**

This would be something super simple like `GET /api/ping` which just returns a 204. Gateways and monitoring tools can use it to check that the services are connected, and can process HTTP requests, and emit alerts otherwise. Infrastructure services like Kubernetes can terminate and restart unhealthy containers.

**Health endpoint**

This would also check connection to databases and storage by a `GET /api/health`. It could check that simple queries like SELECT 1+1 work and that there is free disk space available on the content storage.

On success it would respond with 200 OK, and on failure 503 Service Unavailable. This can be used for more sophisticated monitoring and alerting.

I have checked the API documentation and go source, and did not find any functionality for this.

**Comment by llemeurfr** [comment]
Hi, 

I agree about the use of a ping endpoint, that checks that the server is alive. Added to the lcpserver and lsdserver (frontend is deprecated). 

If you want to check deeper, with read access to the database, the simplest solution is to call 
- LCP Server: `GET /api/licenses` which returns a set of licenses and can be restricted using `?per_page=1` if you wish. 
- LSD Server: `GET /api/licenses` which returns a set of license statuses and can be restricted using `?per_page=1` if you wish. 

Checking the remaining storage space (for encrypted publications) is not doable if you configure the LCP Server the "modern" way, as this server does not practically manipulate encrypted publications but only stores their path. The encryption utility is the tool that puts content in a storage that can be a file system of a S3-type bucket.
