### ISSUE TITLE
Loan extension after the license has expired

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#345]
A common request from license providers is to allow loan extensions (/renew) after the license has expired. As a user, I can borrow a book from my local library bus miss the renewal deadline. In such a case, I would like to reaccess it by extending my loan. 

The License Status Server currently blocks this, as we consider that another patron may have borrowed the ebook after the license has expired, and we don't want to disturb how library servers calculate concurrent access to a given ebook. But limiting the number of concurrent licenses is not a universal constraint, therefore it is good to be able to deactivate this limit.

The solution is to create a new configuration parameter in the License Status Server, named "renew_expired" (bool). Its default value is false (backward compatibility is respected). When set to true, loan extensions are allowed when licenses have expired (licenses are therefore re-activated), but the upper limit (named "potential date end" in LCP) is not reached. 

The consequence is that "expired" is no longer considered a final state for a license.

**Comment by danielweck** [comment]
I haven't looked at Thorium's LSD "state machine" yet, but I think we will need to allow the "renew" action for "expired" license, while also preventing the opening of the publication.
