### ISSUE TITLE
Support multiple databases (MySQL, MSSQL, etc)

### ISSUE THREAD

**Issue by chrisanderton** [readium/readium-lcp-server#5]
Provide a modular way of selecting which database backend to use - currently uses SQLite

Someone has it working with MSSQL

Need to check the code for how SQLite is implemented - may already be modular and just be a case of configuration (and documentation)

**Comment by llemeurfr** [comment]
SQLite and MySQL are supported. 
Let's close this generic issue in favor of a specific MS SQL one when needed.
