### ISSUE TITLE
HTTP / TLS in the LCP and LSD servers, to test API clients (Let's Encrypt)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-lcp-server#75]
There is a live instance of `readium-lcp-server` available at: https://rcs-test.edrlab.org/8990/manage/
Note that this is out-of-date as the server code in the `feature/newdb` branch is changing rapidly, and there is no continuous integration process.
This deployment is based on the Docker config available at https://github.com/clebeaupin/readium-lcp-server-docker/tree/features/crossplatform which is suitable for the upcoming `feature/newdb` (well, with a few changes required in `config.yaml`)

As you can see, https://rcs-test.edrlab.org is HTTPS ( https://51.254.202.70 )
However, individual developers might want to be able to quickly deploy their personal server build, and/or to test their client apps. Ideally, these tests would be conducted under SSL / TLS to ensure that the integration of HTTP / HTTPS libs on the client side work as expected.

So, just to record my thoughts on this, here is a simple **Let's Encrypt** "patch" for the LCP / LSD server Go code:

`lcpserver/lcpserver.go`:
https://github.com/readium/readium-lcp-server/blob/feature/newdb/lcpserver/lcpserver.go#L136

``` go
    if err := s.ListenAndServe(); err != nil {
        log.Println("Error " + err.Error())
    }
```

=> replace with:

``` go
log.Fatal(s.ListenAndServeTLS("", ""))
```

(or, detect the `https://` prefix in `config.Config.LcpServer.PublicBaseUrl` to trigger TLS support)

`lcpserver/server/server.go`:
https://github.com/readium/readium-lcp-server/blob/feature/newdb/lcpserver/server/server.go
=> add import `"rsc.io/letsencrypt"`
=> in `func New(...)`, add:

``` go
var m letsencrypt.Manager
if err := m.CacheFile("letsencrypt.cache"); err != nil {
    log.Fatal(err)
}
```

Note: the `letsencrypt.cache` is needed separately for the TLS certificates (see the README in https://github.com/rsc/letsencrypt ).
=> in `s := &Server{ Server: http.Server{...}}`, add:

``` go
TLSConfig: &tls.Config{
    GetCertificate: m.GetCertificate,
},
```

More information:
https://letsencrypt.org

**Comment by llemeurfr** [comment]
Implementers are using Nginx for getting https. Let's close the issue, the info about Let's Encrypt TLS implem may still be useful in the future.
